# Generated by Django 6.0.4 on 2026-04-13 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="skills",
            field=models.ManyToManyField(
                blank=True,
                related_name="users",
                to="platform_app.skill",
                verbose_name="Навыки пользователя",
            ),
        ),
    ]
