# Generated by Django 6.0.4 on 2026-04-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0005_joboffer"),
    ]

    operations = [
        migrations.AddField(
            model_name="joboffer",
            name="contact_link",
            field=models.CharField(
                blank=True,
                help_text="Например: https://t.me/employer_hr",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="is_read_by_employer",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="joboffer",
            name="is_read_by_student",
            field=models.BooleanField(default=False),
        ),
    ]
