# Generated by Django 6.0.4 on 2026-04-24 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_app",
            "0006_joboffer_contact_link_joboffer_is_read_by_employer_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="avatar",
            field=models.ImageField(blank=True, null=True, upload_to="avatars/"),
        ),
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500, verbose_name="О себе"),
        ),
    ]
