# Generated by Django 6.0.4 on 2026-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0007_user_avatar_user_bio"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_verified",
            field=models.BooleanField(default=False, verbose_name="Верифицирован"),
        ),
    ]
