# Generated by Django 5.1.2 on 2026-05-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0011_lessonprogress_watched_seconds_lessonvideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action_type",
            field=models.CharField(
                choices=[
                    ("course_created", "Course created"),
                    ("lesson_created", "Lesson created"),
                    ("video_uploaded", "HLS video uploaded"),
                    ("quiz_updated", "Quiz updated"),
                    ("lesson_completed", "Урок завершен"),
                    ("quiz_passed", "Квиз пройден"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "date"], name="platform_ap_user_id_6586b8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="activitylog",
            index=models.Index(
                fields=["user", "date", "action_type"],
                name="platform_ap_user_id_55be48_idx",
            ),
        ),
    ]
