# Generated by Django 5.1.2 on 2026-05-07 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0012_alter_activitylog_action_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="github",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="linkedin",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="location",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="telegram",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
