# Generated by Django 5.1.2 on 2026-05-08 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0013_user_github_user_linkedin_user_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="type",
            field=models.CharField(
                choices=[
                    ("video", "Video"),
                    ("text", "Text"),
                    ("quiz", "Quiz"),
                    ("final_exam", "Final exam"),
                ],
                default="video",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="explanation",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="question",
            name="is_multiple",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="question",
            name="lesson",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="platform_app.lesson",
            ),
        ),
        migrations.CreateModel(
            name="LessonAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="lesson_attachments/")),
                ("original_name", models.CharField(blank=True, max_length=255)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="platform_app.lesson",
                    ),
                ),
            ],
            options={
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="platform_app.course",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.AddField(
            model_name="lesson",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="lessons",
                to="platform_app.module",
            ),
        ),
        migrations.CreateModel(
            name="QuizConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("passing_score_percentage", models.IntegerField(default=80)),
                ("max_attempts", models.IntegerField(default=3)),
                ("penalty_hours", models.IntegerField(default=24)),
                (
                    "time_limit_minutes",
                    models.IntegerField(default=0, help_text="0 = без ограничения"),
                ),
                (
                    "lesson",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_config",
                        to="platform_app.lesson",
                    ),
                ),
            ],
        ),
    ]
