# Generated by Django 5.1.2 on 2026-05-08 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "platform_app",
            "0014_lesson_is_published_lesson_type_question_explanation_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lessonprogress",
            name="attempts_used",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="blocked_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lessonprogress",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
