# Generated by Django 6.0.4 on 2026-05-13 05:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0015_lessonprogress_attempts_used_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vacancy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=160, verbose_name="Название вакансии"),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Компания"
                    ),
                ),
                (
                    "description",
                    models.TextField(max_length=4000, verbose_name="Описание"),
                ),
                (
                    "requirements",
                    models.TextField(
                        blank=True, max_length=3000, verbose_name="Требования"
                    ),
                ),
                (
                    "work_format",
                    models.CharField(
                        choices=[
                            ("remote", "Удалённо"),
                            ("office", "В офисе"),
                            ("hybrid", "Гибрид"),
                            ("any", "Любой формат"),
                        ],
                        default="any",
                        max_length=20,
                        verbose_name="Формат работы",
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Полная занятость"),
                            ("part_time", "Частичная занятость"),
                            ("internship", "Стажировка"),
                            ("project", "Проектная работа"),
                        ],
                        default="full_time",
                        max_length=20,
                        verbose_name="Тип занятости",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="Локация"
                    ),
                ),
                (
                    "salary_from",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Зарплата от"
                    ),
                ),
                (
                    "salary_to",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Зарплата до"
                    ),
                ),
                (
                    "contact_link",
                    models.CharField(
                        blank=True,
                        help_text="Например: https://t.me/hr",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Черновик"),
                            ("published", "Опубликована"),
                            ("closed", "Закрыта"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employer",
                    models.ForeignKey(
                        limit_choices_to={"role": "employer"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancies",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Работодатель",
                    ),
                ),
                (
                    "skills",
                    models.ManyToManyField(
                        blank=True,
                        related_name="vacancies",
                        to="platform_app.skill",
                        verbose_name="Навыки",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VacancyApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, max_length=1200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Отправлен"),
                            ("viewed", "Просмотрен"),
                            ("accepted", "Принят"),
                            ("rejected", "Отклонён"),
                            ("withdrawn", "Отозван"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("is_read_by_student", models.BooleanField(default=True)),
                ("is_read_by_employer", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vacancy_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "vacancy",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="platform_app.vacancy",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["status", "-created_at"], name="platform_ap_status_03e321_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancy",
            index=models.Index(
                fields=["employer", "status"], name="platform_ap_employe_303724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancyapplication",
            index=models.Index(
                fields=["student", "-created_at"], name="platform_ap_student_cb22c7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancyapplication",
            index=models.Index(
                fields=["vacancy", "status"], name="platform_ap_vacancy_a12b75_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancyapplication",
            index=models.Index(
                fields=["is_read_by_student"], name="platform_ap_is_read_f98bdc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="vacancyapplication",
            index=models.Index(
                fields=["is_read_by_employer"], name="platform_ap_is_read_94a175_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="vacancyapplication",
            unique_together={("vacancy", "student")},
        ),
    ]
