# Generated by Django 5.1.2 on 2026-05-24 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("platform_app", "0016_vacancy_vacancyapplication_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="sequential_unlock_enabled",
            field=models.BooleanField(default=False),
        ),
    ]
